### ISSUE TITLE
Could not broadcast input array

### ISSUE THREAD

**Issue by megapro17** [hjchoi95/fast_jigsaw_puzzle_solver#1]
`python merge_image.py Gt 35 35 test -v`
```
Traceback (most recent call last):
  File "R:\fast_jigsaw_puzzle_solver\merge_image.py", line 42, in <module>
    main(sys.argv[1:], config)
  File "R:\fast_jigsaw_puzzle_solver\merge_image.py", line 31, in main
    merger.save_merged_image(OUTPUT_DIRECTORY + "/" + OUTPUT_FILENAME)
  File "R:\fast_jigsaw_puzzle_solver\modules\merger.py", line 111, in save_merged_image
    whiteboard[y_offset: y_offset + cell_h, x_offset: x_offset + cell_w] = paste
ValueError: could not broadcast input array from shape (36,55,3) into shape (37,55,3)
```
I honestly can't understand the magic happening in your program, I just wanted to solve my picture
Also, it shows a warning in the beginning:
```
R:\fast_jigsaw_puzzle_solver\modules\merger.py:125: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  raw_imgs_norm = np.array(self.raw_imgs) / 256 #normalize
```
If can send my picture if you need it

**Comment by megapro17** [comment]
oh, it's because some pictures was with different resolution, 36x55 and 37x55. after running `mogrify -resize 37!x55! *.jpg` it worked correctly

**Comment by hjchoi95** [comment]
Would you mind sending me the picture (or simply dimension of your original picture) for me to reproduce the error?

Also, my algorithm doesn't guarantee complete reconstruction, especially if you slice images to smaller fragments. Being able to always solve any picture is a research topic on it's own, and I focused mainly on time complexity optimization rather than accurate reconstruction.

Check out jigsaw puzzle solver on google scholar! There are so many different possible solutions possible for this problem :)

**Comment by megapro17** [comment]
I did fragments manually with photoshop because I don't have original picture. It's divided by 35x35 parts. I tried to use another algorithm, it couldn't solve it neither. Maybe picture is damaged somehow. Don't waste too much time on it...
![Gt-Beq-gp4I](https://user-images.githubusercontent.com/16743370/112910326-d0405480-90fb-11eb-986e-35a9b0e08cdc.jpg)
This logo should be on picture
![image](https://user-images.githubusercontent.com/16743370/112910493-21e8df00-90fc-11eb-8056-0cb9a341266f.png)

**Comment by hjchoi95** [comment]
The result you gave me is quite expected for my current algorithm, especially given really small pieces. Maybe less than 10x10 fragments might give you better result.
I originally started this project for fun, but now I am thinking about how I could improve my algorithm to do merging better. I'm pretty sure there are a lot of rooms left for improvements! (maybe some time in the future though)

+maybe I should rename slice.py to generate_fragments.py or something like that. Just for clarity.
